spring:
  application:
    name: Hope
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://175.178.25.118:5432/gdjqyy
    username: postgres
    password: 7307913.5t5t
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 80
  shutdown: graceful
vBrowser:
  host: 127.0.0.1
  port: 9000
  userId: 123456